name: Build

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  APP_DATABASE_URL: ${{ vars.APP_DATABASE_URL }}
  APP_API_KEY: ${{ vars.APP_API_KEY }}
  APP_SIGNUP_URL: ${{ vars.APP_SIGNUP_URL }}
  APP_GOOGLE_LOGIN_URL: ${{ vars.APP_GOOGLE_LOGIN_URL }}
  APP_MANUAL_LOGIN_URL: ${{ vars.APP_MANUAL_LOGIN_URL }}
  APP_REFRESH_TOKEN_URL: ${{ vars.APP_REFRESH_TOKEN_URL }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install cargo tools
        run: |
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          cargo binstall --no-confirm just wasm-pack
          cargo install stylance-cli
      - name: Install NodeJs dependencies
        run: npm ci
      - name: Build
        run:  just build
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "dist"

  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
